apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-itkannadigaru
  labels:
    app: chatbot-itkannadigaru
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-itkannadigaru
  template:
    metadata:
      labels:
        app: chatbot-itkannadigaru
    spec:
      containers:
      - name: chatbot-itkannadigaru
        image: replace
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-itkannadigaru-service
spec:
  type: LoadBalancer
  selector:
    app: chatbot-itkannadigaru
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
